version: '3'
services:
  hismith_nginx:
    image: nginx:latest
    container_name: hismith_nginx
    ports:
      - "80:80"
    depends_on:
      - hismith_php
    networks:
      - hismith_network
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
      - ./logs:/var/log/nginx

  hismith_postgres:
    image: postgres:latest
    container_name: hismith_postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./docker/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - hismith_network

  hismith_php:
    image: php:fpm
    container_name: hismith_php
    volumes:
      - .:/var/www/html:rw
      # - ./logs/php-fpm/:/var/log/
      - ./docker/php/:/usr/local/etc/php/conf.d/
    networks:
      - hismith_network

networks:
  hismith_network:
